### ISSUE TITLE
can't generte NotoColorEmoji.ttf

### ISSUE THREAD

**Issue by GershonLin** [C1710/blobmoji#33] opened 2018-10-19 07:50 UTC
follow the README.md, i excute make -j4, but its giving below error:
'''
...
uchars = "".join ([unichr(cp) for cp in cps if not is_vs(cp)])
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
make: *** [Makefile:215: NotoColorEmoji.ttf] Error 1
'''
i modify emoji_builder.py, change unichr(i) to
'''
def unichar(i):
try:
return unichr(i)
except ValueError:
return "".join(("\U%08x" % i).decode('unicode-escape'))
'''
excute make again, fail with follow error:
'''
Traceback (most recent call last):
File "third_party/color_emoji/emoji_builder.py", line 579, in 
main (sys.argv)
File "third_party/color_emoji/emoji_builder.py", line 525, in main
glyph_name = get_glyph_name_from_gsub (uchars, font, unicode_cmap.cmap)
File "third_party/color_emoji/emoji_builder.py", line 33, in get_glyph_name_from_gsub
first_glyph = cmap_dict[ord (string[0])]
KeyError: 55356
make: *** [NotoColorEmoji.ttf] Error 1
'''
how can i successfully generte NotoColorEmoji.ttf?

**Comment by C1710** [comment] 2018-10-19 20:09
So that first error message suggests that there's a problem with parsing a character's name.
However I just checked all the names in `png/128` and it didn't show anything awkward.
I'm just tried building the font from a fresh copy and it worked without any problems.

But just to be sure - did you render any new emojis from the SVG folder and do you have the correct tools installed?

But after all, I don't know very much about the font generating scripts myself - I didn't write any of these since this is just a fork of the original Noto emoji repository 😅

**Comment by GershonLin** [comment] 2018-10-21 18:00
I didn't render a custom SVG image.The make command does not display a tool error and the tool is properly installed.The error show that there is not a corresponding unicode in the cmap table,i am not sure if it is read from the NotoColorEmoji.tmpl.ttx.tmpl file.

'''
Looking for images matching 'build/compressed_pngs/emoji_u*.png'.
Found images for 253 characters in 'build/compressed_pngs/emoji_u*.png'.
Traceback (most recent call last):
  File "third_party/color_emoji/emoji_builder.py", line 577, in <module>
    main (sys.argv)
  File "third_party/color_emoji/emoji_builder.py", line 523, in main
    glyph_name = get_glyph_name_from_gsub (uchars, font, unicode_cmap.cmap)
  File "third_party/color_emoji/emoji_builder.py", line 31, in get_glyph_name_from_gsub
    first_glyph = cmap_dict[ord (string[0])]
KeyError: 55356
make: *** [NotoColorEmoji.ttf] Error 1
rm NotoColorEmoji.tmpl.ttx build/emoji/emoji_u1f44f.png
'''

If need additional configuration or operations when execute the make command?

**Comment by C1710** [comment] 2018-10-21 18:19
55356 is `D83C` in hexadecimal. And there is no Unicode codepoint `D83C`.  
Additional symbols shouldn't cause any problems for the font itself (there are only problems for the EmojiCompat font), otherwise it wouldn't support Emoji 11 and I wouldn't be able to build it myself.

But could you please post the actual character sequence that caused this problem?
The codepoints involved should be stored in `codes`, so you'd simply need to print the content of this list...

**Comment by GershonLin** [comment] 2018-10-22 04:35
like file emoji_u1f4aa.png, unichr(int("1f44a", 16)) has an error(python2.7),so i use "".join(("\U%08x" % i).decode('unicode-escape')), it is why 'D83C' appear.

I print the cmap table in the get_glyph_name_from_gsub method (emoji_builder.py).
as follows:
'''
{0: 'uni0000', 917611: 'uE006B', 917606: 'uE0066', 917612: 'uE006C', 917615: 'uE006F', 13: 'uni000D', 917613: 'uE006D', 917619: 'uE0073', 917625: 'uE0079', 917614: 'uE006E', 917631: 'uE007F', 917607: 'uE0067', 917608: 'uE0068', 32: 'space', 917609: 'uE0069', 917623: 'uE0077', 917620: 'uE0074', 917617: 'uE0071', 917616: 'uE0070', 1042475: 'uFE82B', 917618: 'uE0072', 917552: 'uE0030', 917553: 'uE0031', 917554: 'uE0032', 917555: 'uE0033', 917556: 'uE0034', 917557: 'uE0035', 917558: 'uE0036', 917559: 'uE0037', 917560: 'uE0038', 127988: 'u1F3F4', 917621: 'uE0075', 917622: 'uE0076', 917610: 'uE006A', 128075: 'u1F44B', 128076: 'u1F44C', 128077: 'u1F44D', 128078: 'u1F44E', 8205: 'uni200D', 917624: 'uE0078', 917561: 'uE0039', 128079: 'u1F44F', 917626: 'uE007A', 917601: 'uE0061', 917602: 'uE0062', 917603: 'uE0063', 917604: 'uE0064', 917605: 'uE0065', 127462: 'u1F1E6', 127463: 'u1F1E7', 127464: 'u1F1E8', 127465: 'u1F1E9', 127466: 'u1F1EA', 127467: 'u1F1EB', 127468: 'u1F1EC', 127469: 'u1F1ED', 127470: 'u1F1EE', 127471: 'u1F1EF', 127472: 'u1F1F0', 127473: 'u1F1F1', 127474: 'u1F1F2', 127475: 'u1F1F3', 127476: 'u1F1F4', 127477: 'u1F1F5', 127478: 'u1F1F6', 127479: 'u1F1F7', 127480: 'u1F1F8', 127481: 'u1F1F9', 127482: 'u1F1FA', 127483: 'u1F1FB', 127484: 'u1F1FC', 127485: 'u1F1FD', 127486: 'u1F1FE', 127487: 'u1F1FF'}
'''

Although I directly modify the get_glyph_name_from_gsub method and pass int instead of string unicode, cmap table does not have a corresponding key value.

I am not quite sure where the cmap table is generated from. The /png/128 file cannot find the corresponding value in cmap table in emoji_builder.py code.

**Comment by GershonLin** [comment] 2018-10-22 04:36
like file emoji_u1f4aa.png, unichr(int("1f44a", 16)) has an error(python2.7),so i use "".join(("\U%08x" % i).decode('unicode-escape')), it is why 'D83C' appear.

I print the cmap table in the get_glyph_name_from_gsub method (emoji_builder.py).
as follows:
'''
{0: 'uni0000', 917611: 'uE006B', 917606: 'uE0066', 917612: 'uE006C', 917615: 'uE006F', 13: 'uni000D', 917613: 'uE006D', 917619: 'uE0073', 917625: 'uE0079', 917614: 'uE006E', 917631: 'uE007F', 917607: 'uE0067', 917608: 'uE0068', 32: 'space', 917609: 'uE0069', 917623: 'uE0077', 917620: 'uE0074', 917617: 'uE0071', 917616: 'uE0070', 1042475: 'uFE82B', 917618: 'uE0072', 917552: 'uE0030', 917553: 'uE0031', 917554: 'uE0032', 917555: 'uE0033', 917556: 'uE0034', 917557: 'uE0035', 917558: 'uE0036', 917559: 'uE0037', 917560: 'uE0038', 127988: 'u1F3F4', 917621: 'uE0075', 917622: 'uE0076', 917610: 'uE006A', 128075: 'u1F44B', 128076: 'u1F44C', 128077: 'u1F44D', 128078: 'u1F44E', 8205: 'uni200D', 917624: 'uE0078', 917561: 'uE0039', 128079: 'u1F44F', 917626: 'uE007A', 917601: 'uE0061', 917602: 'uE0062', 917603: 'uE0063', 917604: 'uE0064', 917605: 'uE0065', 127462: 'u1F1E6', 127463: 'u1F1E7', 127464: 'u1F1E8', 127465: 'u1F1E9', 127466: 'u1F1EA', 127467: 'u1F1EB', 127468: 'u1F1EC', 127469: 'u1F1ED', 127470: 'u1F1EE', 127471: 'u1F1EF', 127472: 'u1F1F0', 127473: 'u1F1F1', 127474: 'u1F1F2', 127475: 'u1F1F3', 127476: 'u1F1F4', 127477: 'u1F1F5', 127478: 'u1F1F6', 127479: 'u1F1F7', 127480: 'u1F1F8', 127481: 'u1F1F9', 127482: 'u1F1FA', 127483: 'u1F1FB', 127484: 'u1F1FC', 127485: 'u1F1FD', 127486: 'u1F1FE', 127487: 'u1F1FF'}
'''

Although I directly modify the get_glyph_name_from_gsub method and pass int instead of string unicode, cmap table does not have a corresponding key value.

I am not quite sure where the cmap table is generated from. The /png/128 file cannot find the corresponding value in cmap table in emoji_builder.py code.

**Comment by GershonLin** [comment] 2018-10-22 04:37
like file emoji_u1f4aa.png, unichr(int("1f44a", 16)) has an error(python2.7),so i use "".join(("\U%08x" % i).decode('unicode-escape')), it is why 'D83C' appear.

I print the cmap table in the get_glyph_name_from_gsub method (emoji_builder.py).
as follows:
'''
{0: 'uni0000', 917611: 'uE006B', 917606: 'uE0066', 917612: 'uE006C', 917615: 'uE006F', 13: 'uni000D', 917613: 'uE006D', 917619: 'uE0073', 917625: 'uE0079', 917614: 'uE006E', 917631: 'uE007F', 917607: 'uE0067', 917608: 'uE0068', 32: 'space', 917609: 'uE0069', 917623: 'uE0077', 917620: 'uE0074', 917617: 'uE0071', 917616: 'uE0070', 1042475: 'uFE82B', 917618: 'uE0072', 917552: 'uE0030', 917553: 'uE0031', 917554: 'uE0032', 917555: 'uE0033', 917556: 'uE0034', 917557: 'uE0035', 917558: 'uE0036', 917559: 'uE0037', 917560: 'uE0038', 127988: 'u1F3F4', 917621: 'uE0075', 917622: 'uE0076', 917610: 'uE006A', 128075: 'u1F44B', 128076: 'u1F44C', 128077: 'u1F44D', 128078: 'u1F44E', 8205: 'uni200D', 917624: 'uE0078', 917561: 'uE0039', 128079: 'u1F44F', 917626: 'uE007A', 917601: 'uE0061', 917602: 'uE0062', 917603: 'uE0063', 917604: 'uE0064', 917605: 'uE0065', 127462: 'u1F1E6', 127463: 'u1F1E7', 127464: 'u1F1E8', 127465: 'u1F1E9', 127466: 'u1F1EA', 127467: 'u1F1EB', 127468: 'u1F1EC', 127469: 'u1F1ED', 127470: 'u1F1EE', 127471: 'u1F1EF', 127472: 'u1F1F0', 127473: 'u1F1F1', 127474: 'u1F1F2', 127475: 'u1F1F3', 127476: 'u1F1F4', 127477: 'u1F1F5', 127478: 'u1F1F6', 127479: 'u1F1F7', 127480: 'u1F1F8', 127481: 'u1F1F9', 127482: 'u1F1FA', 127483: 'u1F1FB', 127484: 'u1F1FC', 127485: 'u1F1FD', 127486: 'u1F1FE', 127487: 'u1F1FF'}
'''

Although I directly modify the get_glyph_name_from_gsub method and pass int instead of string unicode, cmap table does not have a corresponding key value.

I am not quite sure where the cmap table is generated from. The /png/128 file cannot find the corresponding value in cmap table in emoji_builder.py code.

**Comment by GershonLin** [comment] 2018-10-22 04:38
like file emoji_u1f4aa.png, unichr(int("1f44a", 16)) has an error(python2.7),so i use "".join(("\U%08x" % i).decode('unicode-escape')), it is why 'D83C' appear.

I print the cmap table in the get_glyph_name_from_gsub method (emoji_builder.py).
as follows:
'''
{0: 'uni0000', 917611: 'uE006B', 917606: 'uE0066', 917612: 'uE006C', 917615: 'uE006F', 13: 'uni000D', 917613: 'uE006D', 917619: 'uE0073', 917625: 'uE0079', 917614: 'uE006E', 917631: 'uE007F', 917607: 'uE0067', 917608: 'uE0068', 32: 'space', 917609: 'uE0069', 917623: 'uE0077', 917620: 'uE0074', 917617: 'uE0071', 917616: 'uE0070', 1042475: 'uFE82B', 917618: 'uE0072', 917552: 'uE0030', 917553: 'uE0031', 917554: 'uE0032', 917555: 'uE0033', 917556: 'uE0034', 917557: 'uE0035', 917558: 'uE0036', 917559: 'uE0037', 917560: 'uE0038', 127988: 'u1F3F4', 917621: 'uE0075', 917622: 'uE0076', 917610: 'uE006A', 128075: 'u1F44B', 128076: 'u1F44C', 128077: 'u1F44D', 128078: 'u1F44E', 8205: 'uni200D', 917624: 'uE0078', 917561: 'uE0039', 128079: 'u1F44F', 917626: 'uE007A', 917601: 'uE0061', 917602: 'uE0062', 917603: 'uE0063', 917604: 'uE0064', 917605: 'uE0065', 127462: 'u1F1E6', 127463: 'u1F1E7', 127464: 'u1F1E8', 127465: 'u1F1E9', 127466: 'u1F1EA', 127467: 'u1F1EB', 127468: 'u1F1EC', 127469: 'u1F1ED', 127470: 'u1F1EE', 127471: 'u1F1EF', 127472: 'u1F1F0', 127473: 'u1F1F1', 127474: 'u1F1F2', 127475: 'u1F1F3', 127476: 'u1F1F4', 127477: 'u1F1F5', 127478: 'u1F1F6', 127479: 'u1F1F7', 127480: 'u1F1F8', 127481: 'u1F1F9', 127482: 'u1F1FA', 127483: 'u1F1FB', 127484: 'u1F1FC', 127485: 'u1F1FD', 127486: 'u1F1FE', 127487: 'u1F1FF'}
'''

Although I directly modify the get_glyph_name_from_gsub method and pass int instead of string unicode, cmap table does not have a corresponding key value.

I am not quite sure where the cmap table is generated from. The /png/128 file cannot find the corresponding value in cmap table in emoji_builder.py code.

**Comment by C1710** [comment] 2021-06-21 21:51
I'll close this now as it'll be probably different with [emoji_builder](https://github.com/C1710/emoji_builder) (although in the end it still uses most of the scripts), plus I would recommend using the Dockerfile.

And the issue is pretty old already...

**Closed by C1710** 2021-06-21 21:51 UTC
